In [17]:
# !pip freeze > requirements.txt

**CAPITULO 12: INTRODUCCION A NUMPY**

In [18]:
import numpy as np

In [19]:
#crear un arreglo de 1 dimension con 12 elementos
arreglo_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("Arreglo 1D: ", arreglo_1d)
print("Forma del arreglo 1D: ", arreglo_1d.shape)
print("Tipo de dato del arreglo 1D: ", arreglo_1d.dtype)
print("Número de dimensiones del arreglo 1D: ", arreglo_1d.ndim)

Arreglo 1D:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Forma del arreglo 1D:  (12,)
Tipo de dato del arreglo 1D:  int64
Número de dimensiones del arreglo 1D:  1


In [20]:
#cambiar la forma del arreglo a una matriz de 2x6
arreglo_2d = arreglo_1d.reshape((2, 6))
print("Arreglo 2D:\n", arreglo_2d)
print("Forma del arreglo 2D: ", arreglo_2d.shape)
print("Tipo de dato del arreglo 2D: ", arreglo_2d.dtype)
print("Número de dimensiones del arreglo 2D: ", arreglo_2d.ndim)

Arreglo 2D:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Forma del arreglo 2D:  (2, 6)
Tipo de dato del arreglo 2D:  int64
Número de dimensiones del arreglo 2D:  2


In [21]:
#crear una matriz de 4x4 con valores aleatorios entre 0 y 1
arreglo_aleatorio = np.random.rand(4, 4)
print("Arreglo aleatorio:\n", arreglo_aleatorio)
print("Forma del arreglo aleatorio: ", arreglo_aleatorio.shape)
print("Tipo de dato del arreglo aleatorio: ", arreglo_aleatorio.dtype)
print("Número de dimensiones del arreglo aleatorio: ", arreglo_aleatorio.ndim)

Arreglo aleatorio:
 [[0.94486592 0.21712825 0.5420237  0.45737034]
 [0.18857503 0.9551152  0.34686793 0.50365574]
 [0.93253755 0.74139375 0.86141809 0.79670264]
 [0.42647285 0.10772167 0.19486829 0.02720834]]
Forma del arreglo aleatorio:  (4, 4)
Tipo de dato del arreglo aleatorio:  float64
Número de dimensiones del arreglo aleatorio:  2


**CAPITULO 13: MANIPULACION DE ARRAYS nDIMENSIONALES**

In [22]:
#CREA UN ARREGLO DE 2 DMIENSINES A PARTIR DE UNA LISTA DE LISTAS
arreglo_2d_lista = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Arreglo 2D a partir de lista de listas:\n", arreglo_2d_lista)
print("Forma del arreglo 2D a partir de lista de listas: ", arreglo_2d_lista.shape)
print("Tipo de dato del arreglo 2D a partir de lista de listas: ", arreglo_2d_lista.dtype)

Arreglo 2D a partir de lista de listas:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma del arreglo 2D a partir de lista de listas:  (3, 3)
Tipo de dato del arreglo 2D a partir de lista de listas:  int64


In [23]:
#crear un arreglo de ceros con forma 3x4
arreglo_ceros = np.zeros((3, 4))
print("Arreglo de ceros:\n", arreglo_ceros)
print("Forma del arreglo de ceros: ", arreglo_ceros.shape)
print("Tipo de dato del arreglo de ceros: ", arreglo_ceros.dtype)
print("Número de dimensiones del arreglo de ceros: ", arreglo_ceros.ndim)


Arreglo de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Forma del arreglo de ceros:  (3, 4)
Tipo de dato del arreglo de ceros:  float64
Número de dimensiones del arreglo de ceros:  2


In [24]:
#crear un arreglo de unos con forma 3x4
arreglo_unos = np.ones((2, 2))
print("Arreglo de unos:\n", arreglo_unos)
print("Forma del arreglo de unos: ", arreglo_unos.shape)
print("Tipo de dato del arreglo de unos: ", arreglo_unos.dtype)
print("Número de dimensiones del arreglo de unos: ", arreglo_unos.ndim)


Arreglo de unos:
 [[1. 1.]
 [1. 1.]]
Forma del arreglo de unos:  (2, 2)
Tipo de dato del arreglo de unos:  float64
Número de dimensiones del arreglo de unos:  2


In [25]:
arreglo_unos[1, 1] = 5
print("Arreglo de unos modificado:\n", arreglo_unos)

Arreglo de unos modificado:
 [[1. 1.]
 [1. 5.]]


In [26]:
#crear una matriz identidad de 3x3
arreglo_identidad = np.eye(6)
print("Arreglo identidad:\n", arreglo_identidad)
print("Forma del arreglo identidad: ", arreglo_identidad.shape)
print("Tipo de dato del arreglo identidad: ", arreglo_identidad.dtype)
print("Número de dimensiones del arreglo identidad: ", arreglo_identidad.ndim)


Arreglo identidad:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Forma del arreglo identidad:  (6, 6)
Tipo de dato del arreglo identidad:  float64
Número de dimensiones del arreglo identidad:  2


In [27]:
#crear un arreglo 3d de ceros con forma 2x3x4
arreglo_3d_ceros = np.zeros((2, 3, 4))
print("Arreglo 3D de ceros:\n", arreglo_3d_ceros)
print("Forma del arreglo 3D de ceros: ", arreglo_3d_ceros.shape)
print("Tipo de dato del arreglo 3D de ceros: ", arreglo_3d_ceros.dtype)
print("Número de dimensiones del arreglo 3D de ceros: ", arreglo_3d_ceros.ndim)

Arreglo 3D de ceros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Forma del arreglo 3D de ceros:  (2, 3, 4)
Tipo de dato del arreglo 3D de ceros:  float64
Número de dimensiones del arreglo 3D de ceros:  3


In [28]:
#generar dos arreglos aleatorios de 3x3
# arreglo_aleatorio1 = np.random.rand(3, 3)
# arreglo_aleatorio2 = np.random.rand(3, 3)
arreglo_aleatorio1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arreglo_aleatorio2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [29]:
#concatenar dos arreglos distintos horizontalmente
# arreglo_concatenar_h = np.concatenate((arreglo_aleatorio1, arreglo_aleatorio2), axis=1)
arreglo_concatenar_h = np.hstack((arreglo_aleatorio1, arreglo_aleatorio2))
print("Concatenación horizontal de matrices:\n", arreglo_concatenar_h)


Concatenación horizontal de matrices:
 [[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


In [30]:
#concatenar dos arreglos distintos verticalmente
# arreglo_concatenar_v = np.concatenate((arreglo_aleatorio1, arreglo_aleatorio2), axis=0)
arreglo_concatenar_v = np.vstack((arreglo_aleatorio1, arreglo_aleatorio2))
print("Concatenación vertical de matrices:\n", arreglo_concatenar_v)


Concatenación vertical de matrices:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


**CAPITULO 14: OPERACIONES MATEMATICAS**

In [31]:
dat = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Arreglo original:\n", dat)

Arreglo original:
 [0 1 2 3 4 5 6 7 8 9]


In [32]:
#suma
suma = np.sum(dat)
print("Suma de elementos del arreglo:\n", suma)
#suma acumulada
suma_acumulada = np.cumsum(dat)
print("Suma acumulada de elementos del arreglo:\n", suma_acumulada)
#suma elemento a elemento
suma_elemento_a_elemento = np.add(dat, dat)
print("Suma elemento a elemento de elementos del arreglo:\n", suma_elemento_a_elemento)
#resta elemento a elemento
resta_elemento_a_elemento = np.subtract(dat, dat)
print("Resta elemento a elemento de elementos del arreglo:\n", resta_elemento_a_elemento)
#promedio
promedio = np.mean(dat)
print("Promedio de elementos del arreglo:\n", promedio)
#mediana
mediana = np.median(dat)
print("Mediana de elementos del arreglo:\n", mediana)
#producto
producto = np.prod(dat)
print("Producto de elementos del arreglo:\n", producto)
#varianza
varianza = np.var(dat)
print("Varianza de elementos del arreglo:\n", varianza)
#desviacion estandar
desviacion_estandar = np.std(dat)
print("Desviación estándar de elementos del arreglo:\n", desviacion_estandar)
#maximo
maximo = np.max(dat)
print("Máximo de elementos del arreglo:\n", maximo)
#minimo
minimo = np.min(dat)
print("Mínimo de elementos del arreglo:\n", minimo)
#indice maximo
indice_maximo = np.argmax(dat)
print("Índice del máximo elemento del arreglo:\n", indice_maximo)


Suma de elementos del arreglo:
 45
Suma acumulada de elementos del arreglo:
 [ 0  1  3  6 10 15 21 28 36 45]
Suma elemento a elemento de elementos del arreglo:
 [ 0  2  4  6  8 10 12 14 16 18]
Resta elemento a elemento de elementos del arreglo:
 [0 0 0 0 0 0 0 0 0 0]
Promedio de elementos del arreglo:
 4.5
Mediana de elementos del arreglo:
 4.5
Producto de elementos del arreglo:
 0
Varianza de elementos del arreglo:
 8.25
Desviación estándar de elementos del arreglo:
 2.8722813232690143
Máximo de elementos del arreglo:
 9
Mínimo de elementos del arreglo:
 0
Índice del máximo elemento del arreglo:
 9
