In [9]:
# !pip freeze > requirements.txt

**VIDEO 15: INTEGRACION DE NUMPY CON PANDAS**

In [10]:
import numpy as np
import pandas as pd

In [11]:
data = np.array([[12, 45, 78, 23], [34, 67, 89, 10], [56, 32, 14, 90], [88, 21, 37, 65]])
df = pd.DataFrame(data, columns=["Col1", "Col2", "Col3", "Col4"])
print("DataFrame:")
df

DataFrame:


Col1  Col2  Col3  Col4
0    12    45    78    23
1    34    67    89    10
2    56    32    14    90
3    88    21    37    65

In [12]:
data = {
    "W": [21, 43, 65, 88],
    "X": [54, 76, 23, 12],
    "Y": [87, 98, 41, 73],
    "Z": [32, 22, 80, 56]
}
df2 = pd.DataFrame(data, index=["A", "B", "C", "D"])
print("\nDataFrame with custom index:")
df2


DataFrame with custom index:


W   X   Y   Z
A  21  54  87  32
B  43  76  98  22
C  65  23  41  80
D  88  12  73  56

In [13]:
array = df.to_numpy()
print("\nConverted to NumPy array:")
print(array)


Converted to NumPy array:
[[12 45 78 23]
 [34 67 89 10]
 [56 32 14 90]
 [88 21 37 65]]


In [14]:
df.values

array([[12, 45, 78, 23],
       [34, 67, 89, 10],
       [56, 32, 14, 90],
       [88, 21, 37, 65]])

In [15]:
#calcular el promedio de cada columna usando numpy
mean = np.mean(df, axis=0)
print("\nMean of each column (pandas):")
print(df.mean())
print("\nMean of each column (numpy):")
print(mean)


Mean of each column (pandas):
Col1    47.50
Col2    41.25
Col3    54.50
Col4    47.00
dtype: float64

Mean of each column (numpy):
Col1    47.50
Col2    41.25
Col3    54.50
Col4    47.00
dtype: float64


In [16]:
#calcular el promedio de cada fila usando numpy
mean_row = np.mean(df, axis=1)
print("\nMean of each row (pandas):")
print(df.mean(axis=1))
print("\nMean of each row (numpy):")
print(mean_row)


Mean of each row (pandas):
0    39.50
1    50.00
2    48.00
3    52.75
dtype: float64

Mean of each row (numpy):
0    39.50
1    50.00
2    48.00
3    52.75
dtype: float64
